#! /bin/sh

DIR="$HOME/.config/sxhkd"

pgrep -x sxhkd > /dev/null || sxhkd -c "$DIR"/sxhkdrc "$DIR"/sharedkeys &

bspc monitor -d I II III IV V VI

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Artha state=floating rectangle=620x510+1055+38
bspc rule -a Zathura state=tiled

bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#05B5DD"
bspc config presel_feedback_color "#05B5DD"

# Autostart applications
bash ~/.config/polybar/nova/launch.sh
nitrogen --restore
picom -b -f
dunst &
xbanish
