#+------------------------------------------- Documentation --+
#+ By Raymond:                                                +
#+ https://github.com/slash071                                +
#                                                             +
# What's TPM:                                                 +
# TPM (Tmux Plugin Manager) manages tmux plugins in an        +
# automated manner.                                           +
# It is used to install and load tmux plugins.                +
# https://github.com/tmux-plugins/tpm                         +
#+------------------------------------------------------------+

#+------------------------------------------------- Config ---+
# Enable mouse support
set -g mouse on

# Escape key delay to 50
set -s escape-time 50

# Focus events for terminals that support them
set -g focus-events on

# Increase tmux messages display duration
set -g display-time 2000

# Refresh 'status-left' and 'status-right' more often
set -g status-interval 15

# Increase scrollback buffer size
set -g history-limit 50000

# Upgrade $TERM
set -s default-terminal "screen-256color"

# Keybind to reload source file faster
unbind r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Colors
set -g status-style bg=black,fg=white

# Panes
set -g pane-border-style bg=default,fg=brightblack
set -g pane-active-border-style bg=default,fg=blue
set -g display-panes-colour black
set -g display-panes-active-colour brightblack

# Messages
set -g message-style bg=brightblack,fg=cyan
set -g message-command-style bg=brightblack,fg=cyan

#+--------------------------------------------- Status Bar ---+
# Uncomment ONLY one style at a time, or use the default.
###### <Powerline>
# Bars
#set -g status-left "#[fg=black,bg=blue,bold] #S #[fg=blue,bg=black,nobold,noitalics,nounderscore]"
#set -g status-right "#{prefix_highlight}#[fg=brightblack,bg=black,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] "%H:%M" #[fg=cyan,bg=brightblack,nobold,noitalics,nounderscore]#[fg=black,bg=cyan,bold] #H "
#
# Windows
#set -g window-status-format "#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I #[fg=white,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#W #F #[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
#set -g window-status-current-format "#[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#I #[fg=black,bg=cyan,nobold,noitalics,nounderscore] #[fg=black,bg=cyan]#W #F #[fg=cyan,bg=black,nobold,noitalics,nounderscore]"
#set -g window-status-separator ""

###### <Minimal Powerline>
# Bars
#set -g status-left "#[fg=black,bg=blue,bold] #S #[fg=blue,bg=black,nobold,noitalics,nounderscore]"
#set -g status-right "#{prefix_highlight}#[fg=brightblack,bg=black,nobold,noitalics,nounderscore]#[fg=white,bg=brightblack] "%H:%M" #[fg=blue,bg=brightblack,nobold,noitalics,nounderscore]#[fg=black,bg=blue,bold] #H "
#
# Windows
#set -g window-status-format "#[fg=black,bg=brightblack,nobold,noitalics,nounderscore] #[fg=white,bg=brightblack]#I:#[fg=white,bg=brightblack]#W #F#[fg=brightblack,bg=black,nobold,noitalics,nounderscore]"
#set -g window-status-current-format "#[fg=black,bg=blue,nobold,noitalics,nounderscore] #[fg=black,bg=blue]#I:#[fg=black,bg=blue]#W #F#[fg=blue,bg=black,nobold,noitalics,nounderscore]"
#set -g window-status-separator ""

#+------------------------------------------------ Plugins ---+
#set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'tmux-plugins/tmux-resurrect'
#set -g @plugin 'tmux-plugins/tmux-continuum'

# keep this line at the very bottom of tmux.conf
#run '~/.tmux/plugins/tpm/tpm'
